version: '3.5'

services:
  getaway:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - forniute_api
      - forniute_client
    networks:
      - forniute_network

  forniute_mysql:
    image: mariadb:10.3
    # image: mysql
    command: --default-authentication-plugin=mysql_native_password

    volumes:
      - sql-volume:/var/lib/mysql
      - ./forniute-server/database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: forniute
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql

    ports:
      - 3306:3306
    #   - "33060:33060"
    networks:
      - forniute_network

  forniute_api:
    build: ./forniute-server/
    container_name: forniute_api
    image: forniute-api
    volumes:
      - ./forniute-server/:/usr/src/app
      - /usr/src/app/node_modules
    # ports:
    #   - 9000:9000
    depends_on:
      - forniute_mysql
    networks:
      - forniute_network
  
  forniute_client:
    build: ./forniute-client/
    container_name: forniute_client
    image: forniute-client
    volumes: 
      - ./forniute-client/:/usr/src/app
      - /usr/src/app/node_modules
    # ports:
    #   - 3000:3000
    depends_on:
      - forniute_api
    networks: 
      - forniute_network

networks: 
  forniute_network:
    driver: bridge
    name: forniute_network

volumes:
  sql-volume: